pkg/registry/registry_antrea.csv, pkg/registry/registry_antrea.go
This is to support pod-to-service flows.
=> Add new IPFIX field in Antrea registry

go.mod, go.sum, pkg/exporter/process.go, pkg/registry/build_registry/build_registry.go
=> Change klog version to v2

pkg/registry/registry_antrea.csv, pkg/registry/registry_antrea.go
Add network policy name and namespace fields.
=> Add network policy fields to Antrea registry

go.mod, go.sum, pkg/collector/process.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/exporter/process.go, pkg/registry/build_registry/build_registry.go, pkg/test/exporter_collector_test.go
to keep klog version consistent with Antrea
=> Revert klog from v2 to v1

go.mod, go.sum, pkg/collector/process.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/exporter/process.go, pkg/registry/build_registry/build_registry.go, pkg/test/exporter_collector_test.go
(cherry picked from commit 257952b5a79148eebd0234221285eb62f0ec101d)
=> revert klog from v2 to v1 (#33)

.github/workflows/go.yml
Added CI job through github actions. It checks if unit tests pass or not.
=> Github CI: Create go.yml

CHANGELOG.md, pkg/collector/process_test.go
(cherry picked from commit de77bb84d029c738bc2a9a2370ccc333a3cafbcd)
=> Update CHANGELOG for release v0.2.1

pkg/registry/registry.go, pkg/registry/registry_test.go, pkg/test/exporter_collector_test.go
=> Change reverse information element and const naming

pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go
=> Add RWMutex lock for clients map to prevent concurrent writes

CHANGELOG.md
(cherry picked from commit 4a1cdd3696ea8152ed730c471dd90ee2218cb568)
=> Update CHANGELOG for v0.2.2

pkg/collector/process.go, pkg/entities/record.go, pkg/entities/set.go, pkg/util/util.go
=> Support data encoding with IO stream

Makefile, cmd/collector/collector.go, go.sum, pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/entities/message.go, pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/set_test.go, pkg/entities/testing/mock_record.go, pkg/exporter/process.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/worker.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go
Merging the latest commits from master on to release-0.3.0
=> Implementation of Intermediate Process (#51)

.github/workflows/build.yml, .github/workflows/build_tag.yml, Makefile, build/images/Dockerfile.build.collector
Also add github workflow to push to Antrea org of docker registry.
=> Add docker image for ipfix-collector (cherry picking commit from master branch)

cmd/collector/collector.go
Modify standalone collector code to make it extendable in the future.
=> Simplify standalone collector code

pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/intermediate/aggregate.go
so that it can be packed as fields in IPFIXCollectingProcess/IPFIXAggregationProcess in flow aggregator.
=> Expose collecting process and aggregation process as public struct

pkg/collector/process_test.go, pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/set_test.go, pkg/entities/testing/mock_record.go, pkg/exporter/process.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/worker.go, pkg/test/collector_intermediate_test.go
based on after-merge comments on PR #51
=> Improve intermediate process

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
Before aggregating, valid data records if all the records have
proper values after decoding.
=> Validating data records in aggregation process

.gitignore, Makefile, cmd/collector/collector.go, go.sum, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/intermediate/aggregate.go, pkg/registry/registry_test.go, pkg/test/collector_intermediate_test.go
=> Fix testing problems for TestCollectorToIntermediate and golangci-lint

pkg/collector/process.go, pkg/collector/process_test.go, pkg/entities/ie.go, pkg/intermediate/aggregate_test.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go
- Add handling for IPv6 address with `[]`
- Fix IPv6 encoding issue in `pkg/entities/ie.go`
- Add some testing code for IPv6
=> Improve testing coverage on IPv6

pkg/entities/ie.go, pkg/intermediate/aggregate.go
Log the error values in Encode function to assist debugging.
=> Add log info for debugging

CHANGELOG.md, pkg/collector/process.go, pkg/exporter/process.go, pkg/util/util.go
This PR should be rebases and merged after #133
=> Changes for release v0.4.4

CHANGELOG.md, cmd/collector/collector.go, pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/entities/message_test.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/entities/testing/mock_set.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/intermediate/aggregate_test.go, pkg/producer/kafka_test.go, pkg/test/exporter_collector_test.go, pkg/util/util.go
Cherry picked v0.4.5 commits from release-0.4.0 branch.
=> Cherrypick v0.4.5 changes on to main branch

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/registry/registry.go
This is to add "flowEndReason" field in nonStatsElement list to update the field in the aggregated record as part of Aggregation process.
=> Modify aggregation process to consume flow end reason

.github/workflows/build.yml
Brnach name should be main and not master.
=> Go-IPFIX collector image workflow fix

pkg/entities/set.go
Reverts vmware/go-ipfix#163
This is being done to have this commit part of v0.5.0 release and not 0.4.x release
=> Revert "Fix the Set reset issue"

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
Reverts vmware/go-ipfix#158
This is being done to have this commit part of v0.5.0 release and not 0.4.x release
=> Revert "Modify Aggregation process methods"

pkg/collector/tcp.go, pkg/collector/udp.go, pkg/intermediate/worker.go
=> Improve verbose logging of message information

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/registry/registry.go, pkg/registry/registry_antrea.csv, pkg/test/exporter_collector_test.go
=> Rename of constants for FlowType

cmd/consumer/consumer.go
We should not assume that Kafka broker is already present and ready. 
Have a retry mechanism for consumer initialization.
=> Improve Kafka consumer application

pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/test/exporter_collector_test.go
In the previous fix #227, we ensured listener is closed when calling `cp.Stop()` so that when user wants to establish a new connection, they will have error, which is expected. But that is not enough since user can still write to existing connection because corresponding connection was not closed properly. 
At the time we close connection, if user writes to existing connection, collector will still process one record because it already waits at the next iteration of `conn.Read(buff)`. And it takes a little time to close the connection, so set wait for 1 millisecond before sending next record to make the results more steady.
Additionally, since `conn.Write` is not a reliable way for checking whether the connection is open from client side, we add a `CheckConnToCollector` method for clients …
=> Properly close tcp and udp collector server

go.sum, pkg/collector/process.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/entities/testing/mock_set.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/intermediate/aggregate_test.go, pkg/kafka/producer/convertor/test/flowtype_test.go, pkg/test/util.go
This is to keep the old method as it is and introduce new
one for better performance when adding data records, where additional elements are added in the future.
=> Add new method for adding record with extra elements

pkg/exporter/process.go
Golang Conn objects are "thread-safe" and multiple goroutines may invoke methods
on a Conn simultaneously. The Golang standard library will take care of
serializing the call correctly. So we can remove this extra mutex.
=> Remove conn mutex for exporting process

CHANGELOG.md
Signed-off-by: heanlan <hanlan@vmware.com>
=> update CHANGELOG for v0.5.11

pkg/intermediate/aggregate.go
This PR fixes the throughput burst issues. 
Previously we reset `totalCount` and `deltaCount` static elements after the record is sent. As the throughput is calculated by `diff(octetTotalCount) / diff(flowEndSeconds)`, the existing `octetTotalCount` should not be reset to 0. 
The PR also adds reset of throughput after the the record is sent. This deals with the condition that a record is sent by both active and inactive expiry interval. The receiver will get two records with the same `flowEndSecond`. In this case, the record sent by inactive expiry interval timeout should have the throughput as 0.
=> Fixed the throughput burst issue

CHANGELOG.md
Signed-off-by: Yanjun Zhou <zhouya@vmware.com>
=> update CHANGELOG for v0.5.12

CHANGELOG.md
=> Revert "update CHANGELOG for v0.5.14"

build/yamls/collector/templates/ipfix-collector.yaml, build/yamls/collector/values.yaml, build/yamls/ipfix-collector.yaml, cmd/collector/collector.go
Add registration of klog flags
Fixes: #306
=> Fix collector klog flag not supported error

pkg/collector/clock.go, pkg/collector/clock_test.go
This is how timers from the standard library behave.
=> Support resetting expired timer in fake clock

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/worker.go
This enables consumers of this library to do some preprocessing on data records included in messages received by the collector, prior to passing on the records to the AggregationProcess. Without this change, a consumer has to either mutate the record objects directly (which may require adding new methods to the Record interface, and these methods may not be very meaningful or may be very specialized), or has to duplicate records and wrap them in a new data set and a new message, which is cumbersome and expensive. With this change, a consumer can duplicate records (quite cheaply, by reusing the IE list), and pass them directly to the AggregationProcess.
Note that we maintain backwards-compatibility. When initializing the AggregationProcess, one can choose whether data will be fed as …
=> Support Records as input for AggregationProcess

pkg/collector/process.go, pkg/collector/process_test.go
GetNumRecordsReceived() was returning the number of IPFIX messages. This was misleading as a message is different from a record, and a message may include multiple records.
We add support for more stats (num messages, num template sets, num data sets, num template records, num data records). At the moment, not all of these stats are exposed through public methods.
GetNumRecordsReceived() is updated to return the number of received data records. GetNumMessagesReceived() is introduced to return the number of received IPFIX messages, which matches the previous implementation of GetNumRecordsReceived().
Finally, we update the collector code so that stats are incremented before sending the message on the channel, instead of after. This seems more correct to me, but also it avoid a possible …
=> Improve received stats in collector

.github/dependabot.yml
In order to update Go module dependencies automatically.
=> Add gomod to dependabot.yml

.github/dependabot.yml, Makefile, go.mod, go.sum, pkg/entities/testing/mock_record.go, pkg/entities/testing/mock_set.go
And disable automatic updates in dependabot.yml
=> Update go.uber.org/mock to v0.5.0
