vmware/go-ipfix

.github/workflows/go.yml, .gitignore, Makefile
Secrets environment variable seems not working for Codecov. Directly added token to yaml file as Antrea did.
Also, to better distinguish unit and integration test coverage in the report, I added the flags to workflow steps and arranged the coverage reports into one folder.
=> Add codecov token and flags for tests

pkg/registry/registry.go, pkg/registry/registry_test.go, pkg/test/exporter_collector_test.go
Change reverse ie naming back to the one with `reverse` prefix.
Reason:
Elastic stack collector in Antrea will take reverse ie and ie with the same name (but different enterprise ID) as duplicates can cannot decode the message correctly. 
Use prefix `reverse` but not `reverse_` is also to keep consistent with elastic definition.
=> Change reverse information element naming

.github/workflows/upload_release_assets.yml, cmd/collector/collector.go
Asset is collector binary.
Added the missing license header in new file collector.go.
=> Add upload release assets github workflow

Makefile, cmd/collector/collector.go, go.sum, pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/entities/message.go, pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/set_test.go, pkg/entities/testing/mock_record.go, pkg/exporter/process.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/worker.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go
Fixes #3 
This PR is based on PR #49 refactor of set and record struct (will need rebase after #49 merged). Changes made:
1. Modify message list in collector to channel as buffer to support multi producers -> multiple consumers
2. Support adding exporter related info `originalObservationDomainId` and `originalExporterIPv4Address` in collecting process
3. Add aggregation related methods to aggregate messages by 5-tuple and correlate records to fill fields.
4. Support multiple workers to process message.
5. Add unit tests and integration test from collector to intermediate process.
=> Implementation of Intermediate Process

CHANGELOG.md
This PR will be merged after merging following PR: https://github.com/vmware/go-ipfix/pull/73
This is to include intermediate process commit.
=> Add changelong for v0.3.0 release

.github/workflows/build.yml, .github/workflows/build_tag.yml, Makefile, build/images/Dockerfile.build.collector
Also add github workflow to push to Antrea org of docker registry.
Image is pushed as antrea/ipfix-collector with latest (for master branch) or release tag (for releases).
=> Add docker image for ipfix-collector

Makefile, go.mod, pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/exporter/process_test.go, pkg/intermediate/aggregate.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go
Cherry-picked unit tests fixes for exporter from #91 
Fixed with collector and intermediate process and added `-race` in unit tests to check for race conditions.
partially fixes #90
=> Fix unit tests with -race for collector and intermediate process

Makefile, pkg/entities/message.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/entities/testing/mock_set.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go
Added a path MTU config parameter for InitExportingProcess function.
For UDP transport, based on path MTU parameter, we make a decision on
the message size. This is optional parameter for TCP transport; TCP
supports max socket buffer size (65535).
Cleaned up AddSetAndSendMsg function a bit as well.
This PR is on top of PR #91. It will be checked in after that PR. Please look for separate commit when reviewing.
=> Message size check for UDP transport

pkg/collector/process_test.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/types.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go
Users cannot create AggregateElements in AggregationInput because elements are not exposed as public. 
Added integration tests to ensure everything work well.
Also refactored test cases in exporter-collector tests.
=> Expose fields in AggregateElements and add integration tests

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
The current delete function acquires lock. In some cases, caller will already
have acquired the lock in the aggregation process. In those cases, we
will need another function that does not acquire lock and deletes the flowKey from the map.
=> Add new delete function in aggregation process

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
The current delete function acquires lock. In some cases, caller will already
have acquired the lock on flowKeyRecordMap in aggregation process. In those
cases, we will need another function that do not acquire lock.
Cherry-picking the commit from release-0.3.0 (v0.3.2) to release-0.4.0
=> Provide delete function in intermediate process without lock

pkg/exporter/process.go, pkg/exporter/process_test.go
so that users can use it to test whether current message size exceeds limit or not
=> Expose pathMTU in exporter

pkg/collector/tcp.go
fixes #124 
For invalid messages, `getMessageLength` may return an invalid value of length which is larger than the slice size. This PR fixes by checking whether the length is valid.
=> Fix slicing problem on tcp collector

cmd/collector/collector.go, go.sum, pkg/collector/process.go, pkg/collector/process_test.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go
Instead of accepting resolved TCP/UDP addresses, exporting and
collecting process takes hostPort and protocol string inputs and
do the addressing resolver job internally to make it easier for the
user.
Fixes #121
=> Modify the input of Exporting and Collecting process

pkg/collector/process.go, pkg/exporter/process.go, pkg/util/util.go
Add DNS resolution in exporter and collector, remove the resolution for tls address because tls will use DNS name for validating certificates.
=> Modify address resolution method in exporter and collector

cmd/collector/collector.go, pkg/util/util.go
Standalone collector takes empty string as address input, which causes the ResolveDNSAddress to throw an error.
=> Fix standalone collector issue

pkg/collector/process.go, pkg/entities/message_test.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/entities/testing/mock_set.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/intermediate/aggregate_test.go, pkg/test/exporter_collector_test.go
Add PrepareSet and ResetSet methods to Set interface.
This is to avoid multiple allocations by the user, for example, when
exporting sets user could allocate the Set only once and re-use it
for exporting multiple records.
PS: In Antrea, the main user of go-ipfix library, this change enables to write better unit tests.
=> Add methods to Set Interface

pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/exporter/process.go, pkg/util/util.go
In exporting and collecting process, simplify the address input
consumption.
This is as per suggestions provided through Antrea PRs, who is the main user of go-ipfix library.
=> Simplify address input consumption

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
Delete the unrequired method of deleting record from record map without lock.
Add a method to get the flow updated time for the flow given flow key.
This is required for PR in Antrea: https://github.com/vmware-tanzu/antrea/pull/1949
=> Modify Aggregation process methods

pkg/entities/set.go
Re-initialize record slice by making it nil for GC to clean
up previous records and references properly.
This led to the issue in Antrea: https://github.com/vmware-tanzu/antrea/issues/2035
=> Fix the Set reset issue

pkg/registry/registry.go, pkg/registry/registry_antrea.csv, pkg/registry/registry_antrea.go
Add some information elements to Antrea registry to prepare support for tcp state transition and deny connection tracking in Antrea.
=> Add new fields for Antrea registry

cmd/collector/collector.go, go.mod, go.sum, pkg/collector/process.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/exporter/process.go, pkg/intermediate/aggregate.go, pkg/intermediate/worker.go, pkg/producer/convertor/test/flowtype1.go, pkg/producer/convertor/test/flowtype2.go, pkg/producer/kafka.go
Revert klog from v2 to v1 to avoid version inconsistency in Antrea and changes for go-ipfix v0.5.x release. Will provide new tag for upgrading klog if this PR https://github.com/vmware-tanzu/antrea/pull/1973 is merged after bumping go-ipfix to v0.5.x
=> Revert klog to v1

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
Reverting this commit 7c0a0ae664f3720eee1d078598e7c825956f3df1.
Reason is that the PR(vmware-tanzu/antrea#1949) that depends on this commit
is not yet ready. And to move the tag of go-ipfix in Antrea for other
PRs this commit should be present in the latest release tags. Therefore,
reverting this.
=> Revert "Modify Aggregation process methods (#158)"

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/registry/registry.go, pkg/registry/registry_antrea.csv
Set correlation of inter-Node flows as not required for deny (drop/reject) egress network policy rule actions. Reason is that deny action will happen only on one node for egress network policy, so only record from source will be received.
=> Aggregation process support for deny connections tracking

.github/workflows/go.yml, .github/workflows/upload_release_assets.yml, Makefile, README.md, build/images/Dockerfile.build.collector, build/yamls/collector/Chart.yaml, build/yamls/collector/templates/ipfix-collector.yaml, build/yamls/collector/values.yaml, build/yamls/ipfix-collector.yaml, ci/check_manifest.sh, hack/generate-manifest-collector.sh, hack/release/prepare-assets.sh, hack/verify-helm.sh
1. Add templates and configuration files to generate the collector manifest
2. Add scripts for preparing and uploading release assets
3. Add corresponding guidance in README to deploy collector
Fixes: #95
=> Create K8s deployment yaml to deploy ipfix-collector

.github/workflows/upload_release_assets.yml
To fix the error: a step cannot have both the `uses` and `run` keys. 
Fixes: #177
=> Fix bug with upload release assets

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
Delete the unrequired method of deleting record from
record map without the lock.
Add a method to get the flow updated time for flow given flow key
Pushing this to main. Based on the Antrea PR progress, I will add this to release-0.5.0 branch.
=> Modify Aggregation process methods (#158)

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
For inter-Node flows, if destination Pod has an ingress reject rule, source node will not commit the flow to conntrack table, so that we cannot do correlation for this case.
=> Modify correlation requirements in aggregation process

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/priorityqueue.go, pkg/intermediate/priorityqueue_test.go, pkg/intermediate/types.go
Aggregation proccess is modified to maintain records in a heap-based on active and inactive expiry
timeouts provided as inputs.
This is needed for providing granular intervals when exporting flow records through flow aggregator in Antrea: https://github.com/vmware-tanzu/antrea/pull/1949
Priority queue code is maintained in a separate package. This can be reused in Antrea flow exporter.
=> Modify aggregation process to maintain record expiry data

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/types.go
If correlation is required, we will set `isMetadataFilled` to true.
if correlation is not required, we will set `isMetadataFilled` to true only when the flow is intra-Node.
`isMetadataFilled` is always true for Intra-Node and ToExternal flows and only applicable for Inter-Node flows that are not required to be correlated. (e.g. flows with Egress deny rule applied)
=> Add support for isMetadataFilled for aggregation process

pkg/entities/record.go
This showed up in performance benchmarking through Antrea.
https://github.com/antrea-io/antrea/pull/2188
=> Remove unnecessary allocation in AddInfoElement method

pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/entities/testing/mock_record.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
Use loop through `orderedElementList` for search element in record because in current use case, number of elements is small. We can consider using ordered map ([example](https://github.com/wk8/go-ordered-map)) if number of elements is large in the future (currently it involves more overhead). 
Did not remove `orderedElementList` when for encoding cases because it will be used in intermediate process when more fields will be added to decoded elements.
fixes #201
=> Remove element map from record

pkg/producer/convertor/test/flowtype_test.go, pkg/producer/kafka.go, pkg/producer/kafka_test.go, pkg/test/collector_producer_test.go
Add methods to send the IPFIX record instead of the whole IPFIX
message, close the sarama kafka go client, get the sarama kafka go client etc.
=> Add more methods to Kafka producer

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/types.go, pkg/test/collector_intermediate_test.go
`SetMetadataFilled` does not take effect on `AggregationRecord` because we are doing it on copy instead of directly onto the record. Modifying value type in `flowRecordMap` will fix this issue.
It was not detected before because usually one deny record for a connection will be exported in our testing settings, which does not involve update for same record.
Also changed `isMetadataFilled` and related function name to `areCorrelatedFieldsFilled` to be more accurate.
=> Fix field set/get by modifying flowRecordMap struct

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/types.go
Some fields like Pod labels will be filled externally on the IPFIX Mediator, areExternalFieldsFilled is an indicator for IPFIX Mediator to check whether these fields has been filled. 
This field is set to false when creating new AggregationFlowRecord.
Setting and utilizing this field is upto the user and not used in go-ipfix library code.
=> Add field AreExternalFieldsFilled for AggregationFlowRecord

pkg/collector/process.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/intermediate/aggregate.go
With these fixes, we see better memory consumption in Antrea
benchmark tests.
Before fix:
```
vagrant@k8s-node-worker-1:~/antrea/pkg/flowaggregator$ go test -test.v -run=none -test.benchmem  -bench=. -memprofile memprofile.out -cpuprofile profile.out
goos: linux
goarch: amd64
pkg: antrea.io/antrea/pkg/flowaggregator
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkIntraNodeFlowRecords
flowaggregator_perf_test.go:446: Num messages received: 1549326
BenchmarkIntraNodeFlowRecords-2           1 120009611181 ns/op 11037419792 B/op 325437079 allocs/op
PASS
ok   antrea.io/antrea/pkg/flowaggregator 120.337s
```
After fix:
```
vagrant@k8s-node-worker-1:~/antrea/pkg/flowaggregator$ go test -test.v -run=none -test.benchmem  -bench=. -memprofile memprofile.out -cpuprofile profile.out
goos: …
```
=> Better buffer management in Collection process

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/intermediate/types.go
Add isIPv4 and isExporterIPv4 fields to aggregated flow record.
This is related to [the issue](https://github.com/antrea-io/antrea/issues/2282) raised in Antrea dual-stack cluster tests.
=> Add more metadata to aggregated flow record

pkg/collector/process.go, pkg/collector/process_test.go, pkg/entities/ie.go, pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/entities/testing/mock_record.go, pkg/entities/testing/mock_set.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/kafka/consumer/protobuf/antrea.pb, pkg/kafka/producer/convertor/test/flowtype_test.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go, pkg/test/util.go
Moving from a slice of pointers to a slice of value for `NewInfoElementWithValue`
object. This saves quite a lot of memory consumption.
Perf results from an Antrea setup:
Before this change:
- From pprof:
```
(pprof) top
Showing nodes accounting for 19.90GB, 96.80% of 20.56GB total
Dropped 172 nodes (cum <= 0.10GB)
Showing top 10 nodes out of 54
flat flat%  sum%    cum  cum%
8.96GB 43.59% 43.59%   8.96GB 43.59% github.com/vmware/go-ipfix/pkg/entities.NewInfoElementWithValue (inline)
3.46GB 16.81% 60.40%   6.68GB 32.50% github.com/vmware/go-ipfix/pkg/entities.(*dataRecord).AddInfoElement
3.23GB 15.69% 76.09%   3.23GB 15.69% github.com/vmware/go-ipfix/pkg/entities.DecodeToIEDataType
1.87GB 9.12% 85.21%  11.57GB 56.26% github.com/vmware/go-ipfix/pkg/collector.(*CollectingProcess).handleTCPCli …
```
=> Collector and Intermediate process performance fix

pkg/collector/process.go, pkg/collector/tcp.go, pkg/test/collector_perf_test.go
Partial buffer needs to be retained when doing reads in
a loop; we should not discard it.
Modify the decoding code to make the buffer usage efficient.
Added unit test to verify that.
=> Fix consecutive read issues on TCP connection in the collector process

pkg/collector/process.go, pkg/entities/record.go, pkg/exporter/process.go, pkg/intermediate/aggregate.go
We reduce the allocation of objects and thereby space considerably with this change.
We saw a reduction of 5GB in total.
Before the change:
```
(pprof) exit
~/work/antrea_all/antrea$ go tool pprof -alloc_objects  ../flow_agg_perf/pprof.flow-aggregator.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz 
(pprof) top
Showing nodes accounting for 739671918, 89.56% of 825867623 total
Dropped 297 nodes (cum <= 4129338)
Showing top 10 nodes out of 58
flat  flat%   sum%        cum   cum%
228875070 27.71% 27.71%  228875070 27.71%  github.com/vmware/go-ipfix/pkg/entities.(*baseRecord).GetInfoElementWithValue
213911377 25.90% 53.61%  363609070 44.03%  github.com/vmware/go-ipfix/pkg/collector.(*CollectingProcess).decodeDataSet
115902842 14.03% 67.65%  115902842 14.03% …
```
=> Add perf improvements to cut down allocations

cmd/collector/collector.go, pkg/collector/process.go, pkg/collector/process_test.go, pkg/entities/ie.go, pkg/entities/ie_test.go, pkg/entities/ie_value.go, pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/entities/testing/mock_record.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/kafka/producer/convertor/test/flowtype1.go, pkg/kafka/producer/convertor/test/flowtype2.go, pkg/kafka/producer/convertor/test/flowtype_test.go, pkg/registry/registry.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go, pkg/test/util.go
Instead of relying on the fact that any data type can be interpreted
through interface{} type using their pointer, we move to InfoElementWithValue
interface. For each data type, we implement this interface with a separate struct.
This results in a very big file pkg/entities/ie_value.go
As there is no good support for generic data types in golang, we need to resort to
this.
Fixes one of the tasks in Issue #209 
In the process, we reduced allocations and memory consumed in the performance
test.
Before fix:
```
BenchmarkMultipleExportersToCollector-16    	       1	1392006670 ns/op	347268992 B/op	 5296157 allocs/op
PASS
ok  	github.com/vmware/go-ipfix/pkg/test	1.829s
```
After fix:
```
BenchmarkMultipleExportersToCollector-16    	       1	1346594175 ns/op	237156360 B/op	 4880056 allocs/op …
```
=> Modify the basic structure `NewInfoElementWithValue`

cmd/collector/collector.go, pkg/collector/process_test.go, pkg/entities/ie.go, pkg/entities/ie_test.go, pkg/entities/ie_value.go, pkg/entities/record_test.go, pkg/exporter/process.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go, pkg/kafka/producer/convertor/test/flowtype1.go, pkg/kafka/producer/convertor/test/flowtype2.go, pkg/test/collector_intermediate_test.go, pkg/test/exporter_collector_test.go
There is lot of repeated code. Base structure
can help in removing that.
=> Remove duplicated code in ie_value.go

pkg/entities/message.go, pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/test/exporter_collector_test.go
We decided to rely on IP fragmentation in the case of UDP transport.
This is going against the IPFIX RFC suggestion. We will revisit if
there are any issues with UDP transport in the future.
=> Remove UDP message size check

pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/testing/mock_record.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
This commit adds GetRecords method to get string format flow records.
It accepts FlowKey to filter the flow records.
Signed-off-by: Yanjun Zhou <zhouya@vmware.com>
=> Add GetRecords method to AggregationProcess

pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/testing/mock_record.go, pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
This commit updates the return type of GetRecords in AggregationProcess from string to map, which makes it more easier to be structured.
Signed-off-by: Yanjun Zhou <zhouya@vmware.com>
=> Update GetRecords in AggregationProcess to return map format records

pkg/exporter/process.go, pkg/exporter/process_test.go, pkg/test/certs.go, pkg/test/exporter_collector_test.go
* move configuration parameters to their own struct and try to use better names
* add ServerName configuration parameter so that clients are able to provide a custom name to check server certificates against
The inspiration is
https://pkg.go.dev/k8s.io/client-go/rest#TLSClientConfig
This is a breaking change for clients, but should be ok since we haven't made a v1.0 release yet for go-ipfix.
Signed-off-by: Antonin Bas <abas@vmware.com>
=> Refactor TLS client config for exporter

pkg/intermediate/aggregate.go
It is quite common for flow-aggregator to receive two flow records with the
same flowEndSeconds value, ending in getting a lot of these harmless logs.
We should increase its verbosity.
Signed-off-by: heanlan <hanlan@vmware.com>
=> Increase log verbosity when skipping aggregation

cmd/collector/collector.go, pkg/registry/registry_antrea.csv, pkg/registry/registry_antrea.go
Add two new fields egressName and egressIP for the visibility of Egress information in flow records.
Changes in Antrea: https://github.com/antrea-io/antrea/pull/5088
=> Add fields for Egress information support

Makefile, build/images/Dockerfile.build.collector, build/images/Dockerfile.build.consumer, go.mod, go.sum
Golang v1.19 is no longer maintained.
=> Bump up Golang to v1.21

pkg/entities/ie.go, pkg/entities/ie_test.go
* Use the copy built-in to copy string bytes to buffer, instead of copying bytes one-by-one with a for loop. This is more efficient (confirmed with new Benchmark functions) and more correct (in case the string includes UTF-8 characters which use more than 1 byte).
* Increase max string length from 65,534 to 65,535.
=> Improve handling of string IEs

pkg/registry/registry_antrea.csv, pkg/registry/registry_antrea.go
Adding L7 visibility fields to the Ipfix table.
l7ProtocolName: field is used to store application layer protocol name, field will be empty if application layer flow is not exported.
httpVals: The field is added to contain all the http values and store them as a string of Json similar to labels. This helps us to store multiple http Vals for a single flow which is possible in case of persistent http.
Mistakenly removed #314
=> Adding L7 visibility fields

pkg/collector/process.go, pkg/collector/tcp.go, pkg/test/collector_perf_test.go
* Gracefully shutdown exporter connections before stopping collector.
* Do not log an error for graceful client shutdown (EOF error).
=> Avoid error logs in BenchmarkMultipleExportersToCollector

pkg/intermediate/aggregate.go, pkg/test/collector_intermediate_test.go
Just like for stats, throughput common fields should only be updated for the "latest" record (based on "flowEndSeconds").
This bug explains why the TestCollectorToIntermediate integration test has been flaky for a long time. In some cases, the record from the destination was processed before the record from the source (we have 2 aggregation workers, so records are not guaranteed to be processed in the order in which they are received). While the destination record has a larger "flowEndSeconds", the "throughput" and "reverseThroughput" common elements were overriden by values from the source record.
=> Fix aggregation bug for throughput common fields

pkg/entities/set_test.go, pkg/intermediate/aggregate_test.go, pkg/test/collector_perf_test.go, pkg/test/util.go
A few new benchmarks, which can be useful when validating improvements to the implementation.
=> Add new Go Benchmarks

pkg/collector/process_test.go, pkg/entities/ie.go
When using the provided slice (provided by the collector) directly, the garbage collector will not be able to release the underlying array while references to the net objects exist. The underlying array is allocated when reading the message from the TCP connection and can be 100s of bytes in size. The collector will typically run aggregation and keep references to the data record and its IEs for some time. During that time, we cannot release the packet buffer, while new packets keep coming in. To avoid the issue, we create a new slice, with a new underlying array, and the packet buffer can be releases as soon as all IEs are instantiated.
=> Create copies of net.IP and net.HardwareAddr when decoding IE values

pkg/collector/process.go, pkg/entities/record.go, pkg/entities/set.go, pkg/entities/testing/mock_set.go
Avoid unnecessary slice creation when adding a record to a set. We implement this change for both data record and template records, but in practice most of the gains will come from data records.
Memory allocations (in bytes) are reduced by around 15% for BenchmarkCollector.
=> Improve memory performance of collector

pkg/registry/registry_antrea.csv, pkg/registry/registry_antrea.go
Keeping the more standardized name for Layer 7 Protocol field
=> Rename l7ProtocolName to appProtocol

Makefile, pkg/registry/build_registry/build_registry.go
go-ipfix does not contain gofmt support, adding the support for it in Makefile
=> Adding make fmt support in go-ipfix

pkg/intermediate/aggregate.go, pkg/intermediate/aggregate_test.go
if exporter sends httpval1 in first export and sends httpvals2 in second we should append both before sending further.
Also the function should take care of deduplicating same TxID items.
=> Update Flow aggregate field httpVals

cmd/collector/collector.go
In this PR:
1. We disable printing records whenever we receive it. Instead, we store records in a string array.
2. Add http listener and handler to receive request to return or reset records.
The reason we do this change is because we want to reduce the time we use to retrieve logs.
Previously, using `kubectl logs` will take lots of time to get the logs. And the time depends on the number of records inside the IPFIX collector Pod. The time range is ~0.8s to 4s. After above changes, the time is reduced to ~80ms.
Functionality has been tested in this PR: https://github.com/antrea-io/antrea/actions/runs/7201229562/job/19617317869?pr=5770
=> Improve IPFIX collector

pkg/registry/registry_antrea.csv, pkg/registry/registry_antrea.go
Add a new field `egressNodeName` for the visibility of Egress information in flow records.
=> Add "egressNodeName" field for Egress information support

build/yamls/collector/templates/ipfix-collector.yaml, build/yamls/ipfix-collector.yaml
The ipfix-collector YAML manifest should no longer reference the VMware Harbor registry. The image should be pulled from DockerHub.
See https://github.com/antrea-io/antrea/issues/6003
=> Stop referencing the VMware Harbor registry for ipfix-collector

pkg/collector/process.go, pkg/intermediate/aggregate.go, pkg/intermediate/worker.go, pkg/kafka/producer/kafka.go
This is a small improvement: the message channel retrieved from the collecting process should be "receive-only".
=> Return receive-only channel in GetMsgChan()

go.mod, go.sum, pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/tcp.go, pkg/collector/udp.go
Previously, in case of a decoding error (e.g., an unknown template ID in a data set), the goroutine responsible for decoding messages would be stopped, but the client would not be deleted. This would lead to a deadlock as subsequent messages could not be written to the packetChan channel for the client, effectively breaking the UDP collecting process completely. To avoid this issue, we log an error when decoding fails, but keep the client alive. Note that for IPFIX over UDP, there is no way to notify a single UDP client of an error (with TCP, we can close the connection if we want). This is also why the template refresh mechanism exists.
We also fix possible race conditions in the UDP collecting process: all access to the clients map should be protected by locking the mutex.
=> Fix how decoding errors are handled for UDP clients in collector

pkg/collector/udp.go, pkg/entities/set.go
The correct recommended default is 600s, not 1800s. 1800s is the recommended default for templateLifeTime (3 times
templateRefreshTimeout).
We also update the UDP collector process to timeout the client after templateLifeTime instead of templateRefreshTimeout. This makes more sense as templateLifeTime is a collector process configuration parameter, while templateRefreshTimeout is for the exporter process.
=> Use correct default value for templateRefreshTimeout

pkg/exporter/process.go, pkg/exporter/process_test.go
There were a couple of issues:
* ConnToCollector is exposed to the consumers of the library, and in Antrea we call ConnToCollector whenever sending a record fails. So the library itself should not call ConnToCollector as this is inherently racy. For example, it is possible for templateRefCh to be closed twice, despite the isChanClosed test (check-then-act race). We could add a mutex and a boolean, but I feel like it is better to just let consumer call ConnToCollector.
* When the exporter process is sending over UDP, there was a typo where a `break` was used instead of `return`. The `break` statement breaks from the select case, and not from the surrounding for loop, so the goroutine would never terminate.
=> Fix connection close in exporter process

go.mod
The "target" of the v0.10.0 tag was "mutated" (the tag was created, then deleted, then created again with a different target commit). This should never be done for a Go module and can create issues for consumers of the module, as the original version will be cached in module proxies, and there will be a discrepancy between module proxies and the version control repository (this can lead to checksum mismatch issues).
The best practice in that case seems to be to retract the invalid version, and release a new one (we will release v0.10.1 in our case).
=> Retract version v0.10.0

pkg/exporter/process.go, pkg/exporter/process_test.go
This is a partial reversal of d072ed8.
It turns out that the check can actually be useful as it can detect that the collector ("server" side) has closed its side of the connection, and this can be used as a signal to close our side of the connection as well. This can happen when a process using our collector implementation is closed, but no TCP RST is received when sendign a data set (in particular, this can happen when running in K8s and using a virtual IP to connect to the collector). This check can detect the issue much faster than relying on a keep-alive timeout. Furthermore, a client of this library could end up blocking if the connection has not timed out yet and the send buffer is full.
=> Restore check for closed TCP connection in exporter process

pkg/exporter/process.go
The default for the template refresh timeout is 600s, not 1800s. This should have been modified as part of #353.
=> Fix invalid function comment for InitExportingProcess

.github/dependabot.yml
This repo currently uses actions which use a deprecated Node.js version. Dependabot will make sure that we use up-to-date actions.
=> Update Github Actions with Dependabot

README.md, build/yamls/kafka-flow-collector.yaml
- For confluent images (Kafka and Zookeeper), we now use the standard images from the confluentinc docker.io organization.
- For the kafka-consumer image, we use antrea/kafka-consumer.
=> Stop using projects.registry.vmware.com registry for Kafka images

.github/workflows/go.yml, codecov.yaml
We need to use a token to upload coverage data.
We can also disable coverage data search, as we already provide the list of files (a single file in our case) to include in the report.
=> Bump codecov/codecov-action to v4

pkg/collector/process.go, pkg/collector/process_test.go, pkg/entities/ie.go, pkg/entities/ie_test.go, pkg/entities/ie_value.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/exporter/process.go, pkg/test/util.go
Introduce a "decoding mode" configuration for the collector process, which can take one of 3 values: Strict, LenientKeepUnknown, LenientDropUnknown. When the mode is Strict, unknown IEs are rejected. This is the default mode and matches the behavior prior to this patch. When the mode is LenientKeepUnknown, unknown IEs are accepted and will be preserved in data records. When the mode is LenientDropUnknown, unknown IEs are accepted but will not be included in data records (creating a mismatch between the data record and the template).
When decoding is not strict and the IE is not found in the registry, the name and type of the IE are not known. Name is kept as an empty string. Type is always set to OctetArray. The length is known as it is included in the template record.
This change …
=> Ability to support unknown IEs when decoding template sets

go.mod, pkg/collector/clock.go, pkg/collector/process.go, pkg/collector/process_test.go
Prior to this change, for every template received by the UDP collector, a new goroutine with a ticker was created, responsible for "expiring" the template after the proper timeout. After expiration, the ticker was stopped and te goroutine would complete (the ticker would only ever tick once, so really a timer should have been used?). If a client were to send a refreshed template, the old goroutine / ticker would not be stopped, and the new template would be deleted by the old goroutine, which is invalid. Additionally, starting a new goroutine every time a template message is received is a bit expensive.
With the new implementation, we use a timer created with time.AfterFunc. All the timers are handled by the go runtime with a single goroutine, making this very lightweight. The timers are …
=> Fix UDP template expiry in collector process

pkg/collector/process.go, pkg/collector/process_test.go
This is particularly useful for UDP collection, as there is no feedback mechanism to let the sender know that the new template is invalid (while with TCP, we can close the connection). If we keep the old template and the sender sends data records which use the new template, we would try to decode them according to the old template, which would cause issues. Instead we will ignore data records for that observation domain and template ID until a new valid template is received.
=> Delete existing template if a new invalid one is received

pkg/collector/clock.go, pkg/collector/clock_test.go, pkg/collector/process.go, pkg/collector/process_test.go, pkg/collector/session.go, pkg/collector/session_test.go, pkg/collector/tcp.go, pkg/collector/udp.go
As per the IPFIX specification, a template is specific to a transport session. Observation domains are not guaranteed to be unique across transport sessions.
When a transport session is closed (TCP connection closed or UDP session timeout), all associated templates are removed. Note that prior to this change, templates associated to a TCP connection were never cleaned up, causing a memory leak.
=> Manage templates per session instead of globally

pkg/collector/process.go, pkg/collector/process_test.go, pkg/test/collector_producer_test.go, pkg/test/exporter_collector_test.go
Having a seprate method to close an "output" channel is an anti-pattern IMO, and it is not clear how library consumers are supposed to use it, in particular in relation to the Stop() method.
Instead, we can close the channel when the Stop() method is closed, and all goroutines which may write to the channel have been stopped. Goroutines which read from the channel can use this as a signal to stop - or can be signalled directly by the goroutine which called Stop() in the first place.
=> Remove CloseMsgChan() method from collector process

pkg/entities/record.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/entities/testing/mock_record.go, pkg/entities/testing/mock_set.go
* Optimize ResetSet to avoid memory allocations
* Add new interface method AddRecordV3 which takes a Record as a parameter (instead of a list of IEs). AddRecordV3 can avoid all memory allocations.
We also add a new GetRecordType method to the Record interface.
=> Improve IPFIX Set implementation

pkg/entities/message.go, pkg/exporter/msg.go, pkg/exporter/process.go, pkg/exporter/process_test.go
As a more efficient and covenient alternative to SendSet.
* SendDataRecords takes a list of data Records (for the same template ID), and breaks them up into multiple IPFIX messages (with one data Set per message) as needed.
* SendDataRecords can take a reusable buffer as a parameter, to avoid repeated memory allocations.
We also introduce the MaxMsgSize input for the Exporter. It will be used by SendDataRecords to determine how to break up the list of Records into multiple messages. When using UDP, MaxMsgSize should be set based on the PMTU (Path MTU) to avoid fragmentation.
=> Add SendDataRecords to IPFIX Exporter

pkg/registry/registry_antrea.csv, pkg/registry/registry_antrea.go
As a way to identify the K8s cluster from which the IPFIX record was exported.
The IE is of type string to allow for enough flexibility. This could be a qualified name or a UUID (for example). It should uniquely identify the cluster (to an external IPFIX collector).
=> Add clusterId IE to Antrea registry

pkg/entities/ie.go, pkg/entities/message.go, pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/set_test.go, pkg/entities/testing/mock_record.go, pkg/exporter/msg.go, pkg/exporter/msg_test.go, pkg/exporter/process.go, pkg/exporter/process_test.go
Calling GetBuffer on a record allocates a new buffer which is then copied to the message buffer. This is not necessary as we can directly encode the IE value to the message buffer.
The recommended way to do that is to call AvailableBuffer on the bytes.Buffer object to get a []byte buffer with enough capacity, then call Append-style methods to add data to the buffer (without allocating new memory).
=> Prevent unnecessary memory allocations in WriteIPFIXMsgToBuffer

pkg/entities/record.go
As far as I know this is an anti-pattern, and I am not sure why it was done this way. baseRecord is just here to help reduce code duplication in dataRecord and templateRecord, which both implement the Record interface.
When embedding Recod in baseRecord, we 1) obfuscate things, making it harder to detect at compile time that one of the record types is missing a method implementation, and 2) increase the size of the baseRecord struct needlessly (after this change the size is reduced from 88B down to 72B on my machine).
=> Do not embed Record interface into baseRecord

pkg/collector/tcp.go
Not a huge improvement all things considered, but an improvement nonetheless and it makes the TCP collector consistent with the UDP collector.
=> Re-use same buffer when receiving messages in TCP collector

pkg/exporter/process.go, pkg/exporter/process_test.go
It is not straightforward for the consumer of the library to determine the maximum message size (for UDP) just based on the PMTU, as the amount to deduct from the PMTU depends on the protocol used for the connection to the exporter (IPv4 or IPv6). The protocol is only known after resolving the collector address, which happens in InitExportingProcess. As a workaround, we add PMTU to the exporter inputs, and let the exporter compute the maximum message size. It is still possible to request a specific maximum message size. If both are provided and the exporter determines that the values are incompatible, an error will be returned.
=> Add Path MTU to Exporter inputs

pkg/exporter/buffered.go, pkg/exporter/buffered_test.go
SendDataRecords was added in #391 as a way to export data records more efficiently. However, this method is not convenient to use for clients which need to mutate the records after sending them (as is the case when aggregation is used). To work around this issue, we introduce a buffered exporter. The buffered exporter wraps the standard exporter process. Whenever a data record is added, it is serialized to a byte buffer immediately, and the buffer is sent when it reaches the maximum message size.
Note that for convenience the buffered exporter also supports JSON records, but in this case it just acts as a passthrough to the regular ("unbuffered") exporter process.
=> Add buffered exporter for IPFIX messages

cmd/collector/collector.go, cmd/collector/collector_test.go
When multiple data records are present in a set / IPFIX message, we need to "split" them so that the API returns them as individual records.
We also drop template records to simplify the implementation.
=> Improve collector program for data sets with multiple records

pkg/exporter/buffered.go, pkg/exporter/buffered_test.go
The record was dropped instead of being added to the template set. Additionally, when a template is sent, buffered messages for the same template ID should be flushed first.
=> Fix template record handling in BufferedExporter

pkg/entities/record.go, pkg/entities/record_test.go, pkg/entities/set.go, pkg/entities/set_test.go, pkg/exporter/buffered_test.go, pkg/exporter/msg_test.go, pkg/exporter/process_test.go
In several cases, GetRecordLength() was returning an invalid value:
- for "decoded" records, the method would always return 0.
- when mutating an IE value with a variable length (e.g., a string element), the cached record length would no longer be correct and the method would return an invalid value.
To avoid this issue, we stop caching the length as part of the Record object, and instead we recompute the length whenever GetRecordLength() is invoked. Typically, this method is only invoked once for a given Record, at the time of exporting the Record, so there should not be any performane impact in a real-life scenario.
We also remove the buffer field from DataRecord (we keep it for TemplateRecord), and we remove the isDecoding field for all records, as it was only used for length tracking …
=> Fix Record length computation

pkg/exporter/buffered.go, pkg/exporter/process.go
The sequence number should be the total number of IPFIX Data Records sent prior to the current message.
=> Fix sequence number incrementing in IPFIX exporter

build/images/Dockerfile.build.collector
These tools are useful to query the ipfix-collector API from inside a container.
=> Add curl and jq to ipfix-collector Docker image

cmd/collector/collector.go, pkg/collector/process.go, pkg/collector/tcp.go, pkg/collector/udp.go, pkg/exporter/process.go
We support providing a list of cipher suites, as well as a min TLS protocol version.
For DTLS, the version cannot be configured (only 1.2 is supported).
=> Support for more TLS config options in Collector and Exporter
